#   COMPOSER
FROM composer:latest as composer

#   PHP BUILDER
FROM php:8.1-fpm as php

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng
-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

ENV APP_ENV prod

# Set working directory
WORKDIR /var/www
COPY cdn /var/www

RUN composer install
RUN mkdir -p /var/www/documents
RUN mkdir -p /var/www/uploads

RUN chown -R www-data:www-data /var/www/documents \
    && chown -R www-data:www-data /var/www/uploads

CMD ["php-fpm"]

COPY docker/testing/cdn/www.conf /usr/local/etc/php-fpm.d/www.conf

