version: '3.5'

services:
  focos_calor_app:
    build:
      dockerfile: $PWD/docker/production/php/Dockerfile
      context: .
    environment:
      CONTAINER_ROLE: "app"
    working_dir: /var/www
    networks:
      - focos_calor_net
    volumes:
      - ./application:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - focos_calor_postgis

  focos_calor_nginx:
    image: nginx:1.14-alpine
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - ./docker/production/nginx/etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www
      - ./docker/logs/:/var/log/nginx/
    depends_on:
      - focos_calor_app
      - focos_calor_postgis
    networks:
      - focos_calor_net

  focos_calor_postgis:
    image: postgis/postgis:15-master
    volumes:
      - ./docker/postgis-data:/var/lib/postgresql
      - ./docker/dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      POSTGRES_DB: focos_calor
      POSTGRES_USER: focos_calor_u5r
      POSTGRES_PASSWORD: focos_calor_9w0
      ALLOW_IP_RANGE: 0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      # - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,pgrouting
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=focos_calor_9w0 pg_isready -h 127.0.0.1 -U focos_calor_u5r -d focos_calor"
    networks:
      - focos_calor_net

networks:
  focos_calor_net:
    driver: bridge

volumes:
  postgis-data: ~
